{"name": "TC02 - Login with invalid credential", "status": "failed", "statusDetails": {"message": "AssertionError: \u001b[31mFAILURE: \u001b[0m\n\u001b[31mtests/web/credential/test_TC02.py\u001b[0m:25 in test_login_with_invalid_credential() -> assert_util.verify_equals(\n\u001b[31msrc/utils/assert_util.py\u001b[0m:29 in ___verify___() -> with check:\n\u001b[31massert_util.py\u001b[0m:30 in ___verify___ -> assert result\n\u001b[31mAssertionError\n\u001b[0m\n\n------------------------------------------------------------\nFailed Checks: 1", "trace": "\u001b[31mFAILURE: \u001b[0m\n\u001b[31mtests/web/credential/test_TC02.py\u001b[0m:25 in test_login_with_invalid_credential() -> assert_util.verify_equals(\n\u001b[31msrc/utils/assert_util.py\u001b[0m:29 in ___verify___() -> with check:\n\u001b[31massert_util.py\u001b[0m:30 in ___verify___ -> assert result\n\u001b[31mAssertionError\n\u001b[0m\n\n------------------------------------------------------------\nFailed Checks: 1"}, "steps": [{"name": "Step 1: Navigate to AQX Trader", "status": "passed", "start": 1756357073757, "stop": 1756357076074}, {"name": "Step 2: Login with invalid username", "status": "failed", "steps": [{"name": "\u2713 Verify error text displays", "status": "passed", "start": 1756357077238, "stop": 1756357080356}, {"name": "\u274c [Expected: True] - [Actual: ] Verify setting button on Top Navigation displays", "status": "failed", "attachments": [{"name": "chrome_28-2025-08_11:58:00.png", "source": "2d10346e-8aa3-46ad-bd22-b5d0ccf80d38-attachment.png", "type": "image/png"}], "start": 1756357080356, "stop": 1756357083148}], "start": 1756357076074, "stop": 1756357080654}], "start": 1756357073757, "stop": 1756357080654, "uuid": "0c673079-46c4-49a8-a0ae-4dd73546e970", "historyId": "06d627098a14ab6790ee993ffc5babc1", "testCaseId": "06d627098a14ab6790ee993ffc5babc1", "fullName": "tests.web.credential.test_TC02#test_login_with_invalid_credential", "labels": [{"name": "parentSuite", "value": "Credential"}]}